// Consolidated points data for all 40k factions

export const POINTS = {
  'Adepta Sororitas': {
    units: {
      'Aestred Thurga and Agathae Dolan': 70,
      'Arco-flagellants': [45, 140],
      'Battle Sisters Squad': 105,
      'Canoness with Jump Pack': 75,
      Canoness: 50,
      Castigator: 170,
      'Celestian Sacresants': [70, 130],
      Daemonifuge: 95,
      Dialogus: 40,
      Dogmata: 45,
      'Dominion Squad': 115,
      Exorcist: 210,
      Hospitaller: 50,
      Imagifier: 65,
      Immolator: 125,
      'Junith Eruita': 90,
      'Ministorum Priest': 50,
      Mortifiers: [70, 140],
      'Morvenn Vahl': 170,
      Palatine: 50,
      'Paragon Warsuits': 210,
      'Penitent Engines': [75, 150],
      'Repentia Squad': [75, 160],
      'Retributor Squad': 105,
      'Saint Celestine': 150,
      Sanctifiers: 100,
      'Seraphim Squad': [80, 160],
      'Sisters Novitiate Squad': 100,
      'Sororitas Rhino': 75,
      'Triumph of Saint Katherine': 235,
      'Zephyrim Squad': [80, 160],
    },
    enhancements: {
      'Army of Faith': {
        'Blade of Saint Ellynor': 15,
        'Divine Aspect': 5,
        'Litanies of Faith': 10,
        'Triptych of the Macharian Crusade': 20,
      },
      'Bringers of Flame': {
        'Fire and Fury': 30,
        'Iron Surplice of Saint Istalela': 10,
        'Manual of Saint Griselda': 20,
        'Righteous Rage': 15,
      },
      'Champions of Faith': {
        'Eyes of the Oracle': 10,
        'Mark of Devotion': 30,
        'Sanctified Amulet': 25,
        'Triptych of Judgement': 15,
      },
      'Hallowed Martyrs': {
        'Chaplet of Sacrifice': 25,
        'Mantle of Ophelia': 20,
        'Saintly Example': 10,
        'Through Suffering, Strength': 25,
      },
      'Penitent Host': {
        'Catechism of Divine Penitence': 20,
        'Psalm of Righteous Judgement': 30,
        'Refrain of Enduring Faith': 25,
        'Verse of Holy Piety': 15,
      },
    },
  },
  'Adeptus Custodes': {
    units: {
      Aleya: 65,
      'Blade Champion': 120,
      'Knight-Centura': 55,
      'Shield-Captain': 130,
      'Shield-Captain in Allarus Terminator Armour': 130,
      'Shield-Captain on Dawneagle Jetbike': 150,
      'Trajann Valoris': 140,
      Valerian: 110,
      'Custodian Guard': [170, 215],
      'Agamatus Custodians': [225, 450],
      'Allarus Custodians': [130, 195, 325, 390],
      'Anathema Psykana Rhino': 75,
      'Aquilon Custodians': [195, 390],
      'Ares Gunship': 580,
      'Caladius Grav-tank': 215,
      'Contemptor-Achillus Dreadnought': 155,
      'Contemptor-Galatus Dreadnought': 165,
      'Coronus Grav-carrier': 200,
      'Custodian Guard with Adrasite and Pyrithite Spears': 250,
      'Custodian Wardens': [210, 260],
      'Orion Assault Dropship': 690,
      'Pallas Grav-attack': 105,
      Prosecutors: [40, 50, 90, 100],
      'Sagittarum Custodians': 225,
      'Telemon Heavy Dreadnought': 225,
      'Venerable Contemptor Dreadnought': 170,
      'Venerable Land Raider': 240,
      'Venatari Custodians': [165, 330],
      'Vertus Praetors': [150, 225],
      Vigilators: [50, 65, 115, 125],
      Witchseekers: [50, 65, 115, 125],
    },
    enhancements: {
      'Auric Champions': {
        'Blade Imperator': 25,
        'Inspirational Exemplar': 10,
        'Martial Philosopher': 30,
        'Veiled Blade': 25,
      },
      'Lions of the Emperor': {
        Admonimortis: 10,
        'Fierce Conqueror': 15,
        Praesidius: 25,
        'Superior Creation': 25,
      },
      'Null Maiden Vigil': {
        'Enhanced Voidsheen Cloak': 10,
        "Huntress' Eye": 15,
        'Oblivion Knigh': 25,
        'Raptor Blade': 5,
      },
      'Shield Host': {
        'Auric Mantle': 15,
        "Castellan's Mark": 20,
        'From the Hall of Armouries': 25,
        Panoptispex: 5,
      },
      'Solar Spearhead': {
        'Adamantine Talisman': 25,
        'Augury Uplink': 35,
        'Honoured Fallen': 15,
        'Veteran of the Kataphraktoi': 10,
      },
      'Talons of the Emperor': {
        'Aegis Projector': 20,
        'Champion of the Imperium': 25,
        'Gift of Terran Artifice': 15,
        'Radiant Mantle': 30,
      },
    },
  },
  'Adeptus Mechanicus': {
    units: {
      'Archaeopter Fusilave': 160,
      'Archaeopter Stratoraptor': 185,
      'Archaeopter Transvector': 150,
      'Belisarius Cawl': 175,
      'Corpuscarii Electro-Priests': [65, 130],
      'Cybernetica Datasmith': 35,
      'Fulgurite Electro-Priests': [70, 140],
      'Ironstrider Ballistarii': [75, 150, 225],
      'Kastelan Robots': [180, 360],
      'Kataphron Breachers': [160, 320],
      'Kataphron Destroyers': [105, 210],
      'Onager Dunecrawler': 155,
      'Pteraxii Skystalkers': [70, 140],
      'Pteraxii Sterylizors': [80, 160],
      'Serberys Raiders': [60, 120],
      'Serberys Sulphurhounds': [55, 110],
      'Servitor Battleclade': 60,
      'Sicarian Infiltrators': [70, 140],
      'Sicarian Ruststalkers': [75, 150],
      'Skitarii Marshal': 35,
      'Skitarii Rangers': 85,
      'Skitarii Vanguard': 95,
      'Skorpius Disintegrator': 165,
      'Skorpius Dunerider': 85,
      'Sydonian Dragoons with Radium Jezzails': [55, 100, 150],
      'Sydonian Dragoons with Taser Lances': [65, 130, 195],
      'Sydonian Skatros': 50,
      'Tech-Priest Dominus': 65,
      'Tech-Priest Enginseer': 55,
      'Tech-Priest Manipulus': 60,
      Technoarcheologist: 45,
    },
    enhancements: {
      'Cohort Cybernetica': {
        'Arch-negator': 10,
        'Emotionless Clarity': 15,
        'Lord of Machines': 20,
        Necromechanic: 25,
      },
      'Data-psalm Conclave': {
        'Data-blessed Autosermon': 20,
        'Mantle of the Gnosticarch': 15,
        'Mechanicus Locum': 10,
        Temporcopia: 25,
      },
      'Explorator Maniple': {
        Artisan: 15,
        Genetor: 25,
        Logis: 20,
        Magos: 15,
      },
      'Haloscreed Battle Clade': {
        'Cognitive Reinforcement': 35,
        'Inloaded Lethality': 15,
        'Sanctified Ordnance': 10,
        'Transoracular Dyad Wafers': 15,
      },
      'Rad-zone Corps': {
        'Autoclavic Denunciation': 15,
        'Malphonic Susurrus': 20,
        'Peerless Eradicator': 20,
        'Radial Suffusion': 25,
      },
      'Skitarii Hunter Cohort': {
        'Battle-sphere Uplink': 30,
        'Cantic Thrallnet': 25,
        'Clandestine Infiltrator': 20,
        'Veiled Hunter': 10,
      },
    },
  },
  Aeldari: {
    units: {
      Asurmen: 125,
      Autarch: 85,
      'Autarch Wayleaper': 80,
      'Avatar of Khaine': 280,
      Baharroth: 115,
      'Corsair Voidreavers': [65, 110],
      'Corsair Voidscarred': [80, 160],
      'Crimson Hunter': 160,
      'D-cannon Platform': 125,
      'Dark Reapers': [90, 195],
      'Death Jester': 90,
      'Dire Avengers': [75, 150],
      'Eldrad Ulthran': 110,
      Falcon: 130,
      Farseer: 70,
      'Farseer Skyrunner': 80,
      'Fire Dragons': [120, 220],
      'Fire Prism': 150,
      Fuegan: 120,
      'Guardian Defenders': 100,
      'Hemlock Wraithfighter': 155,
      'Howling Banshees': [95, 190],
      'Jain Zar': 105,
      Lhykhis: 120,
      'Maugan Ra': 100,
      'Night Spinner': 190,
      Rangers: [55, 110],
      'Shadow Weaver Platform': 75,
      Shadowseer: 60,
      'Shining Spears': [110, 220],
      'Shroud Runners': [80, 160],
      Skyweavers: [95, 190],
      Solitaire: 115,
      Spiritseer: 65,
      Starweaver: 80,
      'Storm Guardians': 100,
      'Striking Scorpions': [85, 150],
      'Swooping Hawks': [85, 190],
      Troupe: [85, 100, 190, 205],
      'Troupe Master': 75,
      'Vibro Cannon Platform': 60,
      Voidweaver: 125,
      Vyper: [65, 130],
      'War Walker': [85, 170],
      Warlock: 45,
      'Warlock Conclave': [55, 130],
      'Warlock Skyrunners': [45, 90],
      'Warp Spiders': [95, 190],
      'Wave Serpent': 125,
      Windriders: [80, 160],
      Wraithblades: 160,
      Wraithguard: 170,
      Wraithknight: 435,
      'Wraithknight with Ghostglaive': 420,
      Wraithlord: 140,

      /* Ynnari are separate in the Munitorium docs */
      'The Visarch': 90,
      'The Yncarne': 260,
      'Ynnari Archon': 85,
      'Ynnari Incubi': [85, 170],
      'Ynnari Kabalite Warriors': 110,
      'Ynnari Raider': 80,
      'Ynnari Reavers': [65, 120],
      'Ynnari Succubus': 45,
      'Ynnari Venom': 70,
      'Ynnari Wyches': 90,
      Yvraine: 100,

      /* forge world models */
      'Phantom Titan': 2100,
      'Revenant Titan': 1100,
    },
    enhancements: {
      'Armored Warhost': {
        'Guiding Presence': 25,
        'Guileful Strategist': 15,
        'Harmonisation Matrix': 30,
        'Spirit Stone of Raelyth': 20,
      },
      'Aspect Host': {
        'Aspect of Murder': 25,
        'Mantle of Wisdom': 30,
        Shimmerstone: 15,
        'Strategic Savant': 15,
      },
      'Devoted of Ynnead': {
        'Borrowed Vigour': 10,
        'Gaze of Ynnead': 15,
        'Morbid Might': 15,
        'Storm of Whispers': 10,
      },
      'Ghosts of the Webway': {
        'Cegorach’s Coil': 25,
        'Mask of Secrets': 15,
        Mistweave: 30,
        'Murder’s Jest': 20,
      },
      'Guardian Battlehost': {
        'Breath of Vaul': 10,
        'Craftworld’s Champion': 25,
        'Ethereal Pathway': 30,
        'Protector of the Paths': 20,
      },
      'Seer Council': {
        'Lucid Eye': 30,
        'Runes of Warding': 25,
        'Stone of Eldritch Fury': 15,
        'Torc of Morai-Heg': 20,
      },
      'Spirit Conclave': {
        'Higher Duty': 25,
        'Light of Clarity': 30,
        'Rune of Mists': 10,
        'Stave of Kurnous': 15,
      },
      Warhost: {
        'Gift of Foresight': 15,
        'Phoenix Gem': 35,
        'Psychic Destroyer': 30,
        'Timeless Strategist': 15,
      },
      'Windrider Host': {
        'Echoes of Ulthanesh': 20,
        'Firstdrawn Blade': 10,
        'Mirage Field': 25,
        'Seersight Strike': 15,
      },
    },
  },
  'Astra Militarum (TODO)': {
    units: {},
    enhancements: {},
  },
  'Black Templars (TODO)': {
    units: {},
    enhancements: {},
  },
  'Blood Angels': {
    units: {
      Astorath: 95,
      'Baal Predator': 125,
      'Blood Angels Captain': 80,
      'Chief Librarian Mephiston': 120,
      'Commander Dante': 120,
      'Death Company Captain': 70,
      'Death Company Captain with Jump Pack': 75,
      'Death Company Dreadnought': 180,
      'Death Company Marines': [85, 160],
      'Death Company Marines with Bolt Rifles': [85, 160],
      'Death Company Marines with Jump Packs': [120, 230],
      Lemartes: 100,
      'Sanguinary Guard': [125, 260],
      'Sanguinary Priest': 75,
      'The Sanguinor': 140,
    },
    enhancements: {
      'Angelic Inheritors': {
        'Blazing Icon': 20,
        'Ordained Sacrifice': 25,
        'Prescient Flash': 20,
        'Troubling Visions': 15,
      },
      'Liberator Assault Group': {
        'Gift of Foresight': 15,
        'Icon of the Angel': 20,
        'Rage-fuelled Warrior': 35,
        'Speed of the Primarch': 25,
      },
      'The Angelic Host': {
        "Archangel's Shard": 15,
        'Artisan of War': 20,
        'Gleaming Pinions': 25,
        'Visage of Death': 15,
      },
      'The Lost Brethren': {
        'Blood Shard': 25,
        "Sanguinius' Grace": 20,
        'To Slay the Warmaster': 15,
        'Vengeful Onslaught': 10,
      },
    },
  },
  'Chaos Daemons (TODO)': {
    units: {},
    enhancements: {},
  },
  'Chaos Knights (TODO)': {
    units: {},
    enhancements: {},
  },
  'Chaos Space Marines': {
    units: {
      'Abaddon the Despoiler': 270,
      'Accursed Cultists': [90, 195],
      'Chaos Bikers': [70, 130],
      'Chaos Land Raider': 220,
      'Chaos Lord': 90,
      'Chaos Lord in Terminator Armour': 95,
      'Chaos Lord with Jump Pack': 80,
      'Chaos Predator Annihilator': 135,
      'Chaos Predator Destructor': 140,
      'Chaos Rhino': 75,
      'Chaos Spawn': 70,
      'Chaos Terminator Squad': [180, 360],
      'Chaos Vindicator': 185,
      Chosen: [125, 250],
      'Cultist Firebrand': 45,
      'Cultist Mob': [50, 100],
      Cypher: 90,
      'Dark Apostle': 65,
      'Dark Commune': 90,
      Defiler: 190,
      'Fabius Bile': 85,
      'Fellgor Beastmen': 70,
      Forgefiend: 180,
      'Haarken Worldclaimer': 90,
      Havocs: 125,
      Helbrute: 130,
      Heldrake: 205,
      'Heretic Astartes Daemon Prince': 165,
      'Heretic Astartes Daemon Prince with Wings': 180,
      'Huron Blackheart': 80,
      'Khorne Lord of Skulls': 450,
      Legionaries: [90, 170],
      'Lord Discordant on Helstalker': 160,
      'Master of Executions': 80,
      'Master of Possession': 60,
      Maulerfiend: 130,
      'Nemesis Claw': [110, 190],
      'Noctilith Crown': 125,
      Obliterators: 160,
      Possessed: [120, 240],
      Raptors: [90, 170],
      Sorcerer: 60,
      'Sorcerer in Terminator Armour': 80,
      'Traitor Enforcer': 55,
      'Traitor Guardsmen Squad': 70,
      'Vashtorr the Arkifane': 175,
      Venomcrawler: 110,
      'Warp Talons': [125, 270],
      Warpsmith: 70,
    },
    enhancements: {
      'Cabal of Chaos': {
        'Eye of Z’desh': 25,
        'Infernal Avatar': 20,
        'Mind Blade': 25,
        'Touched by the Warp': 10,
      },
      'Chaos Cult': {
        'Amulet of Tainted Vigour': 20,
        'Cultist’s Brand': 20,
        'Incendiary Goad': 15,
        'Warped Foresight': 10,
      },
      'Creations of Bile': {
        'Helm of All-seeing': 25,
        'Living Carapace': 15,
        'Prime Test Subject': 35,
        'Surgical Precision': 10,
      },
      Deceptors: {
        'Cursed Fang': 10,
        Falsehood: 10,
        'Shroud of Obfuscation': 15,
        'Soul Link': 5,
      },
      'Dread Talons': {
        'Eater of Dread': 15,
        'Night’s Shroud': 20,
        'Warp-fuelled Thrusters': 20,
        Willbreaker: 10,
      },
      'Fellhammer Siege-host': {
        'Bastion Plate': 10,
        'Iron Artifice': 10,
        'Ironbound Enmity': 15,
        'Warp Tracer': 20,
      },
      'Pactbound Zealots': {
        'Eye of Tzeentch': 15,
        'Intoxicating Elixir': 15,
        'Orbs of Unlife': 15,
        'Talisman of Burning Blood': 15,
      },
      'Renegade Raiders': {
        'Despot’s Claim': 15,
        'Dread Reaver': 15,
        'Mark of the Hound': 25,
        'Tyrant’s Lash': 20,
      },
      'Soulforged Warpack': {
        'Forge’s Blessing': 20,
        'Invigorated Mechatendrils': 15,
        'Tempting Addendum': 25,
        'Soul Harvester': 15,
      },
      'Veterans of the Long War': {
        'Eager for Vengeance': 20,
        'Eye of Abaddon': 15,
        'Mark of Legend': 10,
        'Warmaster’s Gift': 15,
      },
    },
  },
  'Dark Angels (TODO)': {
    units: {},
    enhancements: {},
  },
  'Death Guard (TODO)': {
    units: {},
    enhancements: {},
  },
  'Deathwatch (TODO)': {
    units: {},
    enhancements: {},
  },
  'Drukhari (TODO)': {
    units: {},
    enhancements: {},
  },
  "Emperor's Children (TODO)": {
    units: {},
    enhancements: {},
  },
  'Genestealer Cults (TODO)': {
    units: {},
    enhancements: {},
  },
  'Grey Knights': {
    units: {
      'Brother-Captain': 90,
      'Brother-Captain Stern [Legends]': 90,
      'Brotherhood Champion': 70,
      'Brotherhood Chaplain': 65,
      'Brotherhood Librarian': 80,
      'Brotherhood Techmarine': 70,
      'Brotherhood Terminator Squad': [160, 200, 320, 400],
      'Castellan Crowe': 90,
      'Grand Master': 95,
      'Grand Master in Nemesis Dreadknight': 225,
      'Grand Master Voldus': 110,
      'Grey Knights Relic Razorback [Legends]': 95,
      'Grey Knights Dreadnought [Legends]': 160,
      'Grey Knights Thunderhawk Gunship': 805,
      'Interceptor Squad': [125, 250],
      'Kaldor Draigo [Legends]': 125,
      'Land Raider': 220,
      'Land Raider Crusader': 220,
      'Land Raider Redeemer': 270,
      'Nemesis Dreadknight': 210,
      'Paladin Squad': [180, 225, 360, 450],
      'Purgation Squad': [115, 230],
      'Purifier Squad': [125, 250],
      Razorback: 85,
      Rhino: 80,
      'Stormhawk Interceptor': 160,
      'Stormraven Gunship': 280,
      'Stormtalon Gunship': 170,
      'Strike Squad': [120, 240],
      'Venerable Dreadnought': 140,
    },
    enhancements: {
      'Augurium Task Force': {
        'A Foot in the Future': 15,
        "Doomseer's Amulet": 25,
        'Grimoire of Conjunctions': 10,
        'Shield of Prophecy': 20,
      },
      Banishers: {
        'Pyresoul (Psychic)': 20,
        'Sigil of the Hunt': 10,
        'The Ephemeral Tome': 15,
        'The Sixty-sixth Seal': 25,
      },
      'Brotherhood Strike': {
        'Banishing Wave (Psychic)': 20,
        'Blinding Aura': 10,
        'Purity of Purpose': 15,
        'Tome of Forbidden Ways': 25,
      },
      'Hallowed Conclave': {
        'Eye of the Augurium': 25,
        'Inescapable Judgement (Psychic)': 20,
        'Nemesis Rounds': 10,
        'Sanctic Reaper': 15,
      },
      'Sanctic Spearhead': {
        'Driven by Duty': 10,
        'Quickening Foci': 15,
        'Sigil of Exigence': 30,
        'Spiritus Machina': 25,
      },
      'Warpbane Task Force': {
        'Mandulian Reliquary': 20,
        'Paragon of Sanctity': 10,
        'Phial of the Abyss': 25,
        'Radiant Champion': 15,
      },
    },
  },
  'Imperial Agents (TODO)': {
    units: {},
    enhancements: {},
  },
  'Imperial Knights (TODO)': {
    units: {},
    enhancements: {},
  },
  'Leagues of Votann': {
    units: {
      'Arkanyst Evaluator': 65,
      'Brôkhyr Iron-master': 75,
      'Brôkhyr Thunderkyn': [80, 160],
      'Buri Aegnirssen': 95,
      'Cthonian Beserks': [100, 200],
      'Cthonian Earthshakers': 110,
      'Einhyr Champion': 70,
      'Einhyr Hearthguard': [135, 270],
      Grimnyr: 65,
      'Hearthkyn Warriors': 100,
      'Hekaton Land Fortress': 240,
      'Hernkyn Pioneers': [80, 160],
      'Hernkyn Yaegirs': 90,
      'Ironkin Steeljacks w/ Melee Weapons': [85, 170],
      'Ironkin Steeljacks w/ Volkanite Disintegrators': [85, 170],
      Kâhl: 65,
      'Kapricus Carrier': 75,
      'Kapricus Defender': [70, 140],
      'Memnyr Strategist': 45,
      Sagitaur: 90,
      'Ûthar the Destined': 95,
    },
    enhancements: {
      'Brandfast Oathband': {
        'Precursive Judgement': 15,
        'Signature Restoration': 5,
        'Tactical Alchemy': 10,
        'Trivärg Cyber Implant': 40,
      },
      'Dêlve Assault Shift': {
        'Dêlvwerke Navigator': 25,
        'Multiwave System Jammer': 10,
        Piledriver: 15,
        'Quake Supervisor': 20,
      },
      Hearthband: {
        'Bastion Shield': 25,
        'High Kâhl': 30,
        Ironskein: 10,
        'Quake Multigenerator': 15,
      },
      'Hearthfyre Arsenal': {
        'Calculated Tenacity': 15,
        'Fârstrydr Node': 20,
        'Graviton Vault': 5,
        'Mantle of Elders': 10,
      },
      'Needgaârd Oathband': {
        'Ancestral Crest': 15,
        'Dead Reckoning': 10,
        'Iron Ambassador': 5,
        'Oathbound Specifier': 30,
      },
      'Persecution Prospect': {
        'Eye for Weakness': 25,
        'Nomad Strategist': 20,
        'Surgical Saboteur': 10,
        'Writ of Acquisition': 10,
      },
    },
  },
  Necrons: {
    units: {
      'Annihilation Barge': 105,
      "C'tan Shard of the Deceiver": 285,
      "C'tan Shard of the Nightbringer": 315,
      "C'tan Shard of the Void Dragon": 310,
      'Canoptek Doomstalker': 140,
      'Canoptek Macrocytes': 85,
      'Canoptek Reanimator': 75,
      'Canoptek Scarab Swarms': [40, 80],
      'Canoptek Spyders': [75, 150],
      'Canoptek Tomb Crawlers': 50,
      'Canoptek Wraiths': [110, 220],
      'Catacomb Command Barge': 120,
      Chronomancer: 65,
      'Convergence Of Dominion': [60, 120, 180],
      Cryptothralls: 60,
      Deathmarks: [60, 120],
      'Doom Scythe': 230,
      'Doomsday Ark': 200,
      'Flayed Ones': [60, 120],
      Geomancer: 75,
      'Ghost Ark': 115,
      'Hexmark Destroyer': 75,
      'Illuminor Szeras': 165,
      Immortals: [70, 150],
      'Imotekh the Stormlord': 100,
      'Lokhust Destroyers': [40, 60, 90, 180],
      'Lokhust Heavy Destroyers': [55, 110, 165],
      'Lokhust Lord': 80,
      Lychguard: [85, 170],
      Monolith: 400,
      'Nekrosor Ammentar': 165,
      'Necron Warriors': [90, 200],
      'Night Scythe': 145,
      Obelisk: 300,
      'Ophydian Destroyers': [80, 160],
      'Orikan the Diviner': 80,
      Overlord: 85,
      'Overlord with Translocation Shroud': 85,
      Plasmancer: 55,
      Psychomancer: 55,
      'Royal Warden': 50,
      'Skorpekh Destroyers': [90, 180],
      'Skorpekh Lord': 90,
      Technomancer: 80,
      'Tesseract Vault': 425,
      'The Silent King': 400,
      'Tomb Blades': [75, 150],
      "Transcendent C'tan": 305,
      'Trazyn the Infinite': 75,
      'Triarch Praetorians': [90, 180],
      'Triarch Stalker': 110,
      'Seraptek Heavy Construct': 540,
    },
    enhancements: {
      'Annihilation Legion': {
        'Eldritch Nightmare': 15,
        'Eternal Madness': 25,
        'Ingrained Superiority': 10,
        'Soulless Reaper': 20,
      },
      'Awakened Dynasty': {
        'Enaegic Dermal Bond': 30,
        'Nether-realm Casket': 20,
        'Phasal Subjugator': 35,
        'Veil of Darkness': 20,
      },
      'Canoptek Court': {
        Autodivinator: 15,
        'Dimensional Sanctum': 20,
        'Hyperphasic Fulcrum': 15,
        'Metalodermal Tesla Weave': 10,
      },
      'Hypercrypt Legion': {
        'Arisen Tyrant': 25,
        'Dimensional Overseer': 25,
        'Hyperspatial Transfer Node': 15,
        'Osteoclave Fulcrum': 20,
      },
      'Obeisance Phalanx': {
        'Eternal Conqueror': 25,
        'Honourable Combatant': 10,
        'Unflinching Will': 20,
        'Warrior Noble': 15,
      },
      'Starshatter Arsenal': {
        'Chrono-impedance Fields': 25,
        'Demanding Leader': 10,
        'Dread Majesty': 30,
        'Miniaturised Nebuloscope': 15,
      },
    },
  },
  Orks: {
    units: {},
    enhancements: {},
  },
  'Space Marines': {
    units: {
      'Adrax Agatone': 85,
      'Aethon Shaan': 85,
      'Aggressor Squad': [100, 200],
      Ancient: 50,
      'Ancient in Terminator Armour': 75,
      Apothecary: 50,
      'Apothecary Biologis': 70,
      'Assault Intercessor Squad': [75, 150],
      'Assault Intercessors with Jump Packs': [90, 170],
      'Ballistus Dreadnought': 150,
      'Bladeguard Ancient': 45,
      'Bladeguard Veteran Squad': [80, 170],
      'Brutalis Dreadnought': 160,
      Captain: 80,
      'Captain in Gravis Armour': 80,
      'Captain in Phobos Armour': 70,
      'Captain in Terminator Armour': 95,
      'Captain Sicarius': 85,
      'Captain with Jump Pack': 75,
      'Captain Titus': 90,
      'Centurion Assault Squad': [150, 300],
      'Centurion Devastator Squad': [165, 330],
      Chaplain: 60,
      'Chaplain in Terminator Armour': 75,
      'Chaplain on Bike': 75,
      'Chaplain with Jump Pack': 75,
      'Chief Librarian Tigurius': 75,
      'Company Heroes': 75,
      'Darnath Lysander': 100,
      'Desolation Squad': 200,
      'Devastator Squad': [120, 200],
      Dreadnought: 135,
      'Drop Pod': 70,
      'Eliminator Squad': 85,
      'Eradicator Squad': [100, 200],
      'Firestrike Servo-turrets': [75, 150],
      'Gladiator Lancer': 160,
      'Gladiator Reaper': 160,
      'Gladiator Valiant': 150,
      'Hammerfall Bunker': 175,
      'Heavy Intercessor Squad': [100, 200],
      'Hellblaster Squad': [110, 220],
      Impulsor: 80,
      'Inceptor Squad': [120, 240],
      'Incursor Squad': [80, 160],
      'Infernus Squad': [90, 180],
      'Infiltrator Squad': [100, 200],
      'Intercessor Squad': [80, 160],
      'Invader ATV': 60,
      'Invictor Tactical Warsuit': 125,
      'Iron Father Feirros': 95,
      Judiciar: 70,
      'Kayvan Shrike': 100,
      "Kor'Sarro Khan": 70,
      'Land Raider': 220,
      'Land Raider Crusader': 220,
      'Land Raider Redeemer': 270,
      Librarian: 65,
      'Librarian in Phobos Armour': 70,
      'Librarian in Terminator Armour': 75,
      Lieutenant: 65,
      'Lieutenant in Phobos Armour': 55,
      'Lieutenant in Reiver Armour': 55,
      'Lieutenant with Combi-weapon': 70,
      'Lieutenant Titus': 70,
      'Marneus Calgar': 200,
      'Outrider Squad': [80, 160] /* Invader ATV +60 */,
      'Pedro Kantor': 90,
      'Predator Annihilator': 135,
      'Predator Destructor': 140,
      Razorback: 85,
      'Redemptor Dreadnought': 195,
      'Reiver Squad': [80, 160],
      Repulsor: 180,
      'Repulsor Executioner': 220,
      Rhino: 75,
      'Roboute Guilliman': 340,
      'Scout Squad': [70, 140],
      'Sternguard Veteran Squad': [100, 200],
      'Storm Speeder Hailstrike': 115,
      'Storm Speeder Hammerstrike': 125,
      'Storm Speeder Thunderstrike': 150,
      'Stormhawk Interceptor': 155,
      'Stormraven Gunship': 280,
      'Stormtalon Gunship': 165,
      'Suppressor Squad': 75,
      'Tactical Squad': 140,
      Techmarine: 55,
      'Terminator Assault Squad': [180, 360],
      'Terminator Squad': [170, 340],
      'Tor Garadon': 90,
      'Uriel Ventris': 95,
      'Vanguard Veteran Squad with Jump Packs': [95, 190],
      'Victrix Honour Guard': [110, 220],
      Vindicator: 185,
      "Vulkan He'stan": 100,
      'Wardens of Ultramar': 90,
      Whirlwind: 190,

      /* imperial armour (forge world models) */
      Astraeus: 525,
      'Thunderhawk Gunship': 840,
    },
    enhancements: {
      '1st Company Task Force': {
        'Fear Made Manifest': 30,
        'Iron Resolve': 15,
        'Rites of War': 10,
        "The Imperium's Sword": 25,
      },
      'Anvil Siege Force': {
        'Architect of War': 25,
        'Fleet Commander': 15,
        'Indomitable Fury': 20,
        'Stoic Defender': 15,
      },
      "Emperor's Shield": {
        'Champion of the Feast': 25,
        'Disciple of Rhetoricus': 10,
        'Indomitable Champion': 20,
        'Malodraxian Standard': 20,
      },
      'Firestorm Assault Force': {
        'Adamantine Mantle': 20,
        'Champion of Humanity': 10,
        'Forged in Battle': 15,
        'War-tempered Artifice': 25,
      },
      "Forgefather's Seekers": {
        'Adamantine Mantle': 20,
        'Forged in Battle': 15,
        Immolator: 10,
        'War-tempered Artifice': 25,
      },
      'Gladius Task Force': {
        'Adept of the Codex': 20,
        'Artificer Armour': 10,
        'Fire Discipline': 25,
        'The Honour Vehement': 15,
      },
      'Ironstorm Spearhead': {
        'Adept of the Omnissiah': 35,
        'Master of Machine War': 20,
        'Target Augury Web': 30,
        'The Flesh is Weak': 10,
      },
      'Librarius Conclave': {
        Celerity: 30,
        Fusillade: 35,
        Obfuscation: 20,
        Prescience: 25,
      },
      'Shadowmark Talon': {
        'Blackwing Shroud': 25,
        'Coronal Susurrant': 30,
        'Hunter’s Instincts': 25,
        'Umbral Raptor': 15,
      },
      'Stormlance Task Force': {
        'Feinting Withdrawal': 10,
        'Fury of the Storm': 25,
        'Hunter’s Instincts': 25,
        'Portents of Wisdom': 15,
      },
      'Vanguard Spearhead': {
        'Execute and Redeploy': 20,
        'Ghostweave Cloak': 15,
        'Shadow War Veteran': 30,
        'The Blade Driven Deep': 25,
      },
    },
  },
  'Space Wolves': {
    units: {
      'Arjac Rockfist': 105,
      'Bjorn the Fell-Handed': 170,
      'Blood Claws': [135, 285],
      'Fenrisian Wolves': [40, 80],
      'Grey Hunters': 180,
      'Iron Priest': 60,
      'Logan Grimnar': 110,
      Murderfang: 160,
      'Njal Stormcaller': 85,
      'Ragnar Blackmane': 100,
      'Thunderwolf Cavalry': [115, 230],
      'Ulrik the Slayer': 70,
      'Venerable Dreadnought': 140,
      'Wolf Guard Battle Leader': 65,
      'Wolf Guard Headtakers': [85, 170],
      'Wolf Guard Headtakers and Hunting Wolves': [110, 220],
      'Wolf Guard Terminators': [170, 340],
      'Wolf Priest': 70,
      Wulfen: [85, 170],
      'Wulfen Dreadnought': 145,
      'Wulfen with Storm Shields': [100, 200],
    },
    enhancements: {
      'Champions of Fenris': {
        'Fangrune Pendant': 15,
        'Foes’ Fate': 15,
        Longstrider: 20,
        'Wolves’ Wisdom': 30,
      },
      'Saga of the Beastslayer': {
        'Elder’s Guidance': 20,
        'Helm of the Beastslayer': 15,
        'Hunter’s Guile': 20,
        'Wolf-touched': 15,
      },
      'Saga of the Bold': {
        'Braggart’s Steel': 20,
        Hordeslayer: 15,
        Skjald: 15,
        'Thunderwolf’s Fortitude': 25,
      },
      'Saga of the Hunter': {
        'Fenrisian Grit': 15,
        'Feral Rage': 10,
        'Swift Hunter': 20,
        'Wolf Master': 5,
      },
    },
  },
  "T'au Empire": {
    units: {},
    enhancements: {},
  },
  'Thousand Sons': {
    units: {},
    enhancements: {},
  },
  Tyranids: {
    units: {
      Barbgaunts: [55, 110],
      Biovores: [50, 100, 150],
      Broodlord: 80,
      Carnifexes: [115, 230],
      Deathleaper: 80,
      Exocrine: 140,
      Gargoyles: [85, 170],
      Genestealers: [75, 150],
      Harpy: 215,
      Haruspex: 125,
      'Hive Crone': 200,
      'Hive Guard': [90, 180],
      'Hive Tyrant': 225,
      'Hyperadapted Raveners': 165,
      Hormagaunts: [65, 130],
      Lictor: 60,
      Maleceptor: 170,
      Mawloc: 145,
      'Mucolid Spores': [30, 60],
      Neurogaunts: [45, 90],
      Neurolictor: 80,
      Neurotyrant: 105,
      'Norn Assimilator': 275,
      'Norn Emissary': 260,
      'Old One Eye': 150,
      'Parasite of Mortrex': 80,
      Psychophage: 95,
      Pyrovores: [40, 70, 105],
      Raveners: [75, 150],
      'Ripper Swarms': [25, 40, 50],
      'Screamer-Killer': 145,
      'Spore Mines': [55, 110],
      Sporocyst: 145,
      Termagants: [60, 120],
      Tervigon: 175,
      'The Swarmlord': 220,
      Toxicrene: 150,
      Trygon: 140,
      'Tyranid Warriors with Melee Bio-weapons': [75, 150],
      'Tyranid Warriors with Ranged Bio-weapons': [65, 130],
      Tyrannocyte: 105,
      Tyrannofex: 200,
      'Tyrant Guard': [80, 160],
      Venomthropes: [70, 140],
      "Von Ryan's Leapers": [70, 140],
      'Winged Hive Tyrant': 170,
      'Winged Tyranid Prime': 65,
      Zoanthropes: [100, 200],
    },
    enhancements: {
      'Assimilation Swarm': {
        'Biophagic Flow': 10,
        'Instinctive Defence': 15,
        'Parasitic Biomorphology': 25,
        'Regenerating Monstrosity': 20,
      },
      'Crusher Stampede': {
        'Enraged Reserves': 20,
        'Monstrous Nemesis': 25,
        'Null Nodules': 10,
        'Ominous Presence': 15,
      },
      'Invasion Fleet': {
        'Adaptive Biology': 25,
        'Alien Cunning': 30,
        'Perfectly Adapted': 15,
        'Synaptic Linchpin': 20,
      },
      'Subterranean Assault': {
        'Synaptic Strategy': 15,
        'Tremor Senses': 20,
        'Trygon Prime': 20,
        'Vanguard Intellect': 15,
      },
      'Synaptic Nexus': {
        'Power of the Hive Mind': 10,
        'Psychostatic Disruption': 30,
        'Synaptic Control': 20,
        'The Dirgeheart of Kharis': 15,
      },
      'Unending Swarm': {
        'Adrenalised Onslaught': 15,
        'Naturalised Camouflage': 30,
        'Piercing Talons': 25,
        'Relentless Hunger': 20,
      },
      'Vanguard Onslaught': {
        Chameleonic: 15,
        'Hunting Grounds': 20,
        Neuronode: 20,
        Stalker: 10,
      },
      'Warrior Bioform Onslaught': {
        'Elevated Might': 30,
        'Ocular Adaptation': 20,
        'Sensory Assimilation': 20,
        'Synaptic Tyrant': 10,
      },
    },
  },
  'World Eaters': {
    units: {
      Angron: 360,
      Bloodcrushers: [110, 220],
      Bloodletters: 90,
      Bloodthirster: 305,
      'Chaos Land Raider': 220,
      'Chaos Predator Annihilator': 145,
      'Chaos Predator Destructor': 145,
      'Chaos Rhino': 85,
      'Chaos Spawn': 90,
      'Chaos Terminators': [175, 350],
      'Daemon Prince of Khorne': 200,
      'Daemon Prince of Khorne with wings': 180,
      Defiler: 180,
      Eightbound: [135, 270],
      'Exalted Eightbound': [140, 280],
      'Flesh Hounds': [75, 150],
      Forgefiend: 170,
      Goremongers: 85,
      Helbrute: 120,
      Heldrake: 200,
      Jakhals: [65, 140],
      'Khârn the Betrayer': 100,
      'Khorne Berzerkers': [180, 360],
      'Khorne Lord of Skulls': 505,
      'Lord Invocatus': 110,
      'Lord on Juggernaut': 90,
      'Master of Executions': 60,
      Maulerfiend: 150,
      Skarbrand: 305,
      Slaughterbound: 85,
    },
    enhancements: {
      'Berzerker Warband': {
        'Battle-lust': 10,
        'Berzerker Glaive': 25,
        'Favoured of Khorne': 15,
        'Helm of Brazen Ire': 20,
      },
      'Cult of Blood': {
        'Brazen Form': 25,
        'Butcher Lord': 10,
        'Chosen of the Blood God': 15,
        'Strategic Slaughter': 20,
      },
      'Khorne Daemonkin': {
        'Blade of Endless Bloodshed': 30,
        'Blood-forged Armour': 20,
        'Disciple of Khorne': 15,
        'Icon of War': 25,
      },
      'Possessed Slaughterband': {
        'Frenzied Focus': 20,
        'Killing Clarity': 15,
        'Malicious Vigour': 30,
        'Violent Demise': 10,
      },
      'Goretrack Onslaught': {
        'Aggressive Deployment': 20,
        'Infernal Infusion': 25,
        'Murderous Onslaught': 5,
        'Unleash Hell': 10,
      },
      'Vessels of Wrath': {
        Archslaughterer: 25,
        "Avenger's Crown": 15,
        'Gateways to Glory': 10,
        'Vox-Diabolus': 20,
      },
    },
  },
};
