export const factionData = {
  "units": [
        { name: "Adrax Agatone", tags: ["Character", "Epic Hero", "Salamanders"] },
        { name: "Aethon Shaan", tags: ["Character", "Epic Hero"] },
        { name: "Ancient", tags: ["Character", "Ancient"] },
        { name: "Ancient in Terminator Armour", tags: ["Character", "Ancient"] },
        { name: "Apothecary", tags: ["Character"] },
        { name: "Apothecary Biologis", tags: ["Character", "Gravis"] },
        { name: "Bladeguard Ancient", tags: ["Character", "Ancient"] },
        { name: "Captain", tags: ["Character"] },
        { name: "Captain in Gravis Armour", tags: ["Character", "Gravis"] },
        { name: "Captain in Phobos Armour", tags: ["Character", "Phobos"] },
        { name: "Captain in Terminator Armour", tags: ["Character"] },
        { name: "Captain Sicarius", tags: ["Character", "Epic Hero"] },
        { name: "Captain with Jump Pack", tags: ["Character"] },
        { name: "Chaplain", tags: ["Character"] },
        { name: "Chaplain in Terminator Armour", tags: ["Character"] },
        { name: "Chaplain on Bike", tags: ["Character", "Mounted"] },
        { name: "Chaplain with Jump Pack", tags: ["Character"] },
        { name: "Chief Librarian Tigurius", tags: ["Character", "Epic Hero"] },
        { name: "Darnath Lysander", tags: ["Character", "Epic Hero", "Imperial Fists"] },
        { name: "Iron Father Feirros", tags: ["Character", "Epic Hero"] },
        { name: "Judiciar", tags: ["Character"] },
        { name: "Kayvan Shrike", tags: ["Character", "Epic Hero"] },
        { name: "Kor'Sarro Khan", tags: ["Character", "Epic Hero"] },
        { name: "Librarian", tags: ["Character"] },
        { name: "Librarian in Phobos Armour", tags: ["Character", "Phobos"] },
        { name: "Librarian in Terminator Armour", tags: ["Character"] },
        { name: "Lieutenant", tags: ["Character"] },
        { name: "Lieutenant in Phobos Armour", tags: ["Character", "Phobos"] },
        { name: "Lieutenant in Reiver Armour", tags: ["Character", "Phobos"] },
        { name: "Lieutenant with Combi-weapon", tags: ["Character", "Phobos"] },
        { name: "Lieutenant Titus", tags: ["Character", "Epic Hero"] },
        { name: "Marneus Calgar", tags: ["Character", "Epic Hero"] },
        { name: "Pedro Kantor", tags: ["Character", "Epic Hero", "Imperial Fists"] },
        { name: "Roboute Guilliman", tags: ["Character", "Epic Hero"] },
        { name: "Techmarine", tags: ["Character"] },
        { name: "Tor Garadon", tags: ["Character", "Epic Hero", "Imperial Fists"] },
        { name: "Uriel Ventris", tags: ["Character", "Epic Hero"] },
        { name: "Vulkan He'stan", tags: ["Character", "Epic Hero", "Salamanders"] },
        { name: "Assault Intercessor Squad", modelCount: [5, 10], tags: ["Battleline"], unitOptions: { unitSize: [5, 10] } },
        { name: "Heavy Intercessor Squad", modelCount: [5, 10], tags: ["Battleline", "Gravis"], unitOptions: { unitSize: [5, 10] } },
        { name: "Intercessor Squad", modelCount: [5, 10], tags: ["Battleline"], unitOptions: { unitSize: [5, 10] } },
        { name: "Tactical Squad", modelCount: 10, tags: ["Battleline"] },
        { name: "Aggressor Squad", modelCount: [3, 6], tags: ["Gravis"], unitOptions: { unitSize: [3, 6] } },
        { name: "Assault Intercessors with Jump Packs", modelCount: [5, 10], unitOptions: { unitSize: [5, 10] } },
        { name: "Ballistus Dreadnought", modelCount: 140 },
        { name: "Bladeguard Veteran Squad", modelCount: [3, 6], unitOptions: { unitSize: [3, 6] } },
        { name: "Brutalis Dreadnought", modelCount: 160 },
        { name: "Centurion Assault Squad", modelCount: [3, 6], unitOptions: { unitSize: [3, 6] } },
        { name: "Centurion Devastator Squad", modelCount: [3, 6], unitOptions: { unitSize: [3, 6] } },
        { name: "Company Heroes", modelCount: 4, tags: ["Ancient"] },
        { name: "Desolation Squad", modelCount: 5 },
        { name: "Devastator Squad", modelCount: [5, 10], unitOptions: { unitSize: [5, 10] } },
        { name: "Dreadnought", modelCount: 1 },
        { name: "Drop Pod", modelCount: 1 },
        { name: "Eliminator Squad", modelCount: 3, tags: ["Phobos"] },
        { name: "Eradicator Squad", modelCount: [3, 6], tags: ["Gravis"], unitOptions: { unitSize: [3, 6] } },
        { name: "Firestrike Servo-turrets", modelCount: [1, 2], unitOptions: { unitSize: [1, 2] } },
        { name: "Gladiator Lancer", modelCount: 1 },
        { name: "Gladiator Reaper", modelCount: 1 },
        { name: "Gladiator Valiant", modelCount: 1 },
        { name: "Hammerfall Bunker", modelCount: 1 },
        { name: "Hellblaster Squad", modelCount: [5, 10], unitOptions: { unitSize: [5, 10] } },
        { name: "Impulsor", modelCount: 1 },
        { name: "Inceptor Squad", modelCount: [3, 6], tags: ["Gravis"], unitOptions: { unitSize: [3, 6] } },
        { name: "Incursor Squad", modelCount: [5, 10], tags: ["Phobos"], unitOptions: { unitSize: [5, 10] } },
        { name: "Infernus Squad", modelCount: [5, 10], unitOptions: { unitSize: [5, 10] } },
        { name: "Infiltrator Squad", modelCount: [5, 10], tags: ["Phobos"], unitOptions: { unitSize: [5, 10] } },
        { name: "Invader ATV", modelCount: 1, tags: ["Mounted"] },
        { name: "Invictor Tactical Warsuit", modelCount: 1, tags: ["Phobos"] },
        { name: "Land Raider", modelCount: 1 },
        { name: "Land Raider Crusader", modelCount: 1 },
        { name: "Land Raider Redeemer", modelCount: 1 },
        { name: "Outrider Squad", modelCount: [3, 6], tags: ["Mounted"], unitOptions: { unitSize: [3, 6] } },  // figure out how to handle Invader ATV +60
        { name: "Predator Annihilator", modelCount: 1 },
        { name: "Predator Destructor", modelCount: 1 },
        { name: "Razorback", modelCount: 1 },
        { name: "Redemptor Dreadnought", modelCount: 1 },
        { name: "Reiver Squad", modelCount: [5, 10], tags: ["Phobos"], unitOptions: { unitSize: [5, 10] } },
        { name: "Repulsor", modelCount: 1 },
        { name: "Repulsor Executioner", modelCount: 1 },
        { name: "Rhino", modelCount: 1 },
        { name: "Scout Squad", modelCount: [5, 10], unitOptions: { unitSize: [5, 10] } },
        { name: "Sternguard Veteran Squad", modelCount: [5, 10], unitOptions: { unitSize: [5, 10] } },
        { name: "Storm Speeder Hailstrike", modelCount: 1 },
        { name: "Storm Speeder Hammerstrike", modelCount: 1 },
        { name: "Storm Speeder Thunderstrike", modelCount: 1 },
        { name: "Stormhawk Interceptor", modelCount: 1 },
        { name: "Stormraven Gunship", modelCount: 1 },
        { name: "Stormtalon Gunship", modelCount: 1 },
        { name: "Suppressor Squad", modelCount: 1 },
        { name: "Terminator Assault Squad", modelCount: [5, 10], unitOptions: { unitSize: [5, 10] } },
        { name: "Terminator Squad", modelCount: [5, 10], unitOptions: { unitSize: [5, 10] } },
        { name: "Vanguard Veteran Squad with Jump Packs", modelCount: [5, 10], unitOptions: { unitSize: [5, 10] } },
        { name: "Vindicator", modelCount: 1 },
        { name: "Whirlwind", modelCount: 1 },
        { name: "Astraeus", modelCount: 1 },
        { name: "Thunderhawk Gunship", modelCount: 1 },
      ],
      "detachments": [
        {
          name: "1st Company Task Force",
          "enhancements": [
            { name: "Fear Made Manifest" },
            { name: "Iron Resolve", tags: ["Terminator"] },
            { name: "Rites of War", tags: ["Terminator"] },
            { name: "The Imperium's Sword" },
          ],
        },
        {
          name: "Anvil Siege Force",
          enhancements: [
            { name: "Architect of War" },
            { name: "Fleet Commander", tags: ["Captain"] },
            { name: "Indomitable Fury", tags: ["Gravis"] },
            { name: "Stoic Defender" },
          ],
        },
        {
          name: "Emperor's Shield",
          enhancements: [
            { name: "Champion of the Feast", tags: ["Imperial Fists"] },
            { name: "Disciple of Rhetoricus", tags: ["Imperial Fists+Terminator"] },
            { name: "Indomitable Champion", tags: ["Imperial Fists+Terminator"] },
            { name: "Malodraxian Standard", tags: ["Imperial Fists+Ancient"] },
          ],
          "restrictions": ["Imperial Fists"],
        },
        {
          name: "Firestorm Assault Force",
          enhancements: [
            { name: "Adamantine Mantle" },
            { name: "Champion of Humanity", tags: ["Tacticus"] },
            { name: "Forged in Battle" },
            { name: "War-tempered Artifice", tags: ["Infantry"] },
          ],
        },
        {
          name: "Forgefather's Seekers",
          enhancements: [
            { name: "Adamantine Mantle", tags: ["Salamanders"] },
            { name: "Forged in Battle", tags: ["Salamanders"] },
            { name: "Immolator", tags: ["Salamanders"] },
            { name: "War-tempered Artifice", tags: ["Salamanders+Infantry"] },
          ],
          "restrictions": ["Salamanders"],
        },
        {
          name: "Gladius Task Force",
          enhancements: [
            { name: "Adept of the Codex", tags: ["Captain"] },
            { name: "Artificer Armour" },
            { name: "Fire Discipline" },
            { name: "The Honour Vehement" },
          ],
        },
        {
          name: "Ironstorm Spearhead",
          enhancements: [
            { name: "Adept of the Omnissiah", tags: ["Techmarine"] },
            { name: "Master of Machine War" },
            { name: "Target Augury Web", tags: ["Techmarine"] },
            { name: "The Flesh is Weak" },
          ],
        },
        {
          name: "Librarius Conclave",
          enhancements: [
            { name: "Celerity", tags: ["Psyker"] },
            { name: "Fusillade", tags: ["Psyker"] },
            { name: "Obfuscation", tags: ["Psyker"] },
            { name: "Prescience", tags: ["Psyker"] },
          ]
        },
        {
          name: "Shadowmark Talon",
          enhancements: [
            { name: "Blackwing Shroud", tags: ["Infantry+Raven Guard"] },
            { name: "Coronal Susurrant", tags: ["Phobos+Raven Guard"] },
            { name: "Hunter’s Instincts", tags: ["Raven Guard"] },
            { name: "Umbral Raptor", tags: ["Raven Guard"] },
          ],
          "restrictions": ["Raven Guard"],
        },
        {
          name: "Stormlance Task Force",
          enhancements: [
            { name: "Feinting Withdrawal" },
            { name: "Fury of the Storm", tags: ["Mounted"] },
            { name: "Hunter’s Instincts", tags: ["Mounted"] },
            { name: "Portents of Wisdom" },
          ],
        },
        {
          name: "Vanguard Spearhead",
          enhancements: [
            { name: "Execute and Redeploy", tags: ["Phobos"] },
            { name: "Ghostweave Cloak" },
            { name: "Shadow War Veteran", tags: ["Phobos"] },
            { name: "The Blade Driven Deep", tags: ["Infantry"] },
          ],
        },
      ],
};
