export const factionData = {
  units: [
    { name: 'Broodlord', tags: ['Character', 'Vanguard Invader', 'Psyker', 'Synapse'] },
    { name: 'Deathleaper', tags: ['Character', 'Epic Hero', 'Vanguard Invader'] },
    { name: 'Hive Tyrant', tags: ['Character', 'Monster', 'Psyker', 'Synapse'] },
    {
      name: 'Hyperadapted Raveners',
      tags: ['Character', 'Vanguard Invader', 'Synapse'],
      modelCount: 5,
    },
    { name: 'Neurotyrant', tags: ['Character', 'Monster', 'Psyker', 'Synapse'] },
    { name: 'Old One Eye', tags: ['Character', 'Epic Hero', 'Monster'] },
    { name: 'Parasite of Mortrex', tags: ['Character', 'Vanguard Invader', 'Synapse'] },
    { name: 'Tervigon', tags: ['Character', 'Monster', 'Psyker', 'Synapse'] },
    { name: 'The Swarmlord', tags: ['Character', 'Epic Hero', 'Monster', 'Psyker', 'Synapse'] },
    {
      name: 'Winged Hive Tyrant',
      tags: ['Character', 'Monster', 'Vanguard Invader', 'Psyker', 'Synapse'],
    },
    { name: 'Winged Tyranid Prime', tags: ['Character', 'Vanguard Invader', 'Synapse'] },
    {
      name: 'Gargoyles',
      modelCount: [10, 20],
      unitOptions: { unitSize: [10, 20] },
      tags: ['Battleline', 'Vanguard Invader'],
    },
    {
      name: 'Hormagaunts',
      modelCount: [10, 20],
      unitOptions: { unitSize: [10, 20] },
      tags: ['Battleline'],
    },
    {
      name: 'Termagants',
      modelCount: [10, 20],
      unitOptions: { unitSize: [10, 20] },
      tags: ['Battleline'],
    },
    { name: 'Barbgaunts', modelCount: [5, 10], unitOptions: { unitSize: [5, 10] } },
    { name: 'Biovores', modelCount: [1, 2, 3], unitOptions: { unitSize: [1, 2, 3] } },
    {
      name: 'Carnifexes',
      modelCount: [1, 2],
      unitOptions: { unitSize: [1, 2] },
      tags: ['Monster'],
    },
    { name: 'Exocrine', tags: ['Monster'] },
    {
      name: 'Genestealers',
      modelCount: [5, 10],
      unitOptions: { unitSize: [5, 10] },
      tags: ['Vanguard Invader'],
    },
    { name: 'Harpy', tags: ['Monster', 'Vanguard Invader'] },
    { name: 'Haruspex', tags: ['Monster'] },
    { name: 'Hive Crone', tags: ['Monster', 'Vanguard Invader'] },
    { name: 'Hive Guard', modelCount: [3, 6], unitOptions: { unitSize: [3, 6] } },
    { name: 'Lictor', tags: ['Vanguard Invader'] },
    { name: 'Maleceptor', tags: ['Monster', 'Psyker', 'Synapse'] },
    { name: 'Mawloc', tags: ['Monster', 'Vanguard Invader'] },
    { name: 'Mucolid Spores', modelCount: [1, 2], unitOptions: { unitSize: [1, 2] } },
    { name: 'Neurogaunts', modelCount: [11, 22], unitOptions: { unitSize: [11, 22] } },
    { name: 'Neurolictor', tags: ['Vanguard Invader', 'Synapse'] },
    { name: 'Norn Assimilator', tags: ['Monster', 'Synapse'] },
    { name: 'Norn Emissary', tags: ['Monster', 'Psyker', 'Synapse'] },
    { name: 'Psychophage', tags: ['Monster'] },
    { name: 'Pyrovores', modelCount: [1, 2, 3], unitOptions: { unitSize: [1, 2, 3] } },
    {
      name: 'Raveners',
      modelCount: [3, 6],
      unitOptions: { unitSize: [3, 6] },
      tags: ['Vanguard Invader'],
    },
    { name: 'Ripper Swarms', modelCount: [1, 2, 3], unitOptions: { unitSize: [1, 2, 3] } },
    { name: 'Screamer-Killer', tags: ['Monster'] },
    { name: 'Spore Mines', modelCount: [3, 6], unitOptions: { unitSize: [3, 6] } },
    { name: 'Sporocyst', tags: ['Monster'] },
    { name: 'Toxicrene', tags: ['Monster'] },
    { name: 'Trygon', tags: ['Monster', 'Vanguard Invader'] },
    {
      name: 'Tyranid Warriors with Melee Bio-weapons',
      modelCount: [3, 6],
      unitOptions: { unitSize: [3, 6] },
      tags: ['Synapse'],
    },
    {
      name: 'Tyranid Warriors with Ranged Bio-weapons',
      modelCount: [3, 6],
      unitOptions: { unitSize: [3, 6] },
      tags: ['Synapse'],
    },
    { name: 'Tyrannocyte', tags: ['Monster', 'Vanguard Invader'] },
    { name: 'Tyrannofex', tags: ['Monster'] },
    { name: 'Tyrant Guard', modelCount: [3, 6], unitOptions: { unitSize: [3, 6] } },
    { name: 'Venomthropes', modelCount: [3, 6], unitOptions: { unitSize: [3, 6] } },
    {
      name: "Von Ryan's Leapers",
      modelCount: [3, 6],
      unitOptions: { unitSize: [3, 6] },
      tags: ['Vanguard Invader'],
    },
    {
      name: 'Zoanthropes',
      modelCount: [3, 6],
      unitOptions: { unitSize: [3, 6] },
      tags: ['Psyker', 'Synapse'],
    },
  ],
  detachments: [
    {
      name: 'Assimilation Swarm',
      enhancements: [
        { name: 'Biophagic Flow' },
        { name: 'Instinctive Defence' },
        { name: 'Parasitic Biomorphology' },
        { name: 'Regenerating Monstrosity' },
      ],
    },
    {
      name: 'Crusher Stampede',
      enhancements: [
        { name: 'Enraged Reserves', tags: ['Monster'] },
        { name: 'Monstrous Nemesis', tags: ['Monster'] },
        { name: 'Null Nodules', tags: ['Monster'] },
        { name: 'Ominous Presence', tags: ['Monster'] },
      ],
    },
    {
      name: 'Invasion Fleet',
      enhancements: [
        { name: 'Adaptive Biology' },
        { name: 'Alien Cunning' },
        { name: 'Perfectly Adapted' },
        { name: 'Synaptic Linchpin' },
      ],
    },
    {
      name: 'Subterranean Assault',
      enhancements: [
        { name: 'Synaptic Strategy' },
        { name: 'Tremor Senses' },
        { name: 'Trygon Prime', tags: ['Trygon'] },
        { name: 'Vanguard Intellect' },
      ],
    },
    {
      name: 'Synaptic Nexus',
      enhancements: [
        { name: 'Power of the Hive Mind', tags: ['Psyker'] },
        { name: 'Psychostatic Disruption', tags: ['Synapse'] },
        { name: 'Synaptic Control', tags: ['Synapse'] },
        { name: 'The Dirgeheart of Kharis', tags: ['Synapse'] },
      ],
    },
    {
      name: 'Unending Swarm',
      enhancements: [
        { name: 'Adrenalised Onslaught' },
        { name: 'Naturalised Camouflage' },
        { name: 'Piercing Talons' },
        { name: 'Relentless Hunger' },
      ],
    },
    {
      name: 'Vanguard Onslaught',
      enhancements: [
        { name: 'Chameleonic', tags: ['Vanguard Invader'] },
        { name: 'Hunting Grounds' },
        { name: 'Neuronode' },
        { name: 'Stalker', tags: ['Vanguard Invader'] },
      ],
    },
    {
      name: 'Warrior Bioform Onslaught',
      enhancements: [
        { name: 'Elevated Might' },
        { name: 'Ocular Adaptation', tags: ['Winged Tyranid Prime'] },
        { name: 'Sensory Assimilation', tags: ['Winged Tyranid Prime'] },
        { name: 'Synaptic Tyrant', tags: ['Neurotyrant'] },
      ],
    },
  ],
};
