export const FACTION_NAMES_TO_CODES = {
  "Adepta Sororitas": "sisters",
  "Adeptus Custodes": "custodes",
  "Adeptus Mechanicus": "mechanicus",
  "Aeldari": "aeldari",
  "Astra Militarum": "astra",
  "Black Templars": "blackTemplars",
  "Blood Angels": "bloodAngels",
  "Chaos Daemons": "daemons",
  "Chaos Knights": "chaosKnights",
  "Chaos Space Marines": "chaosMarines",
  "Dark Angels": "darkAngels",
  "Death Guard": "deathGuard",
  "Deathwatch": "deathwatch",
  "Drukhari": "drukhari",
  "Emperor's Children": "emperorsChildren",
  "Genestealer Cults": "gsc",
  "Grey Knights": "greyKnights",
  "Imperial Agents": "imperialAgents",
  "Imperial Fists": "imperialFists",
  "Imperial Knights": "imperialKnights",
  "Iron Hands": "ironHands",
  "Leagues of Votann": "votann",
  "Necrons": "necrons",
  "Orks": "orks",
  "Raven Guard": "ravenGuard",
  "Salamanders": "salamanders",
  "Space Marines": "spaceMarines",
  "Space Wolves": "spaceWolves",
  "T'au Empire": "tau",
  "Thousand Sons": "thousandSons",
  "Tyranids": "tyranids",
  "Ultramarines": "ultramarines",
  "White Scars": "whiteScars",
  "World Eaters": "worldEaters",
};

export const FACTION_NAMES = {
  "sisters": "Adepta Sororitas",
  "blackTemplars": "Black Templars",
  "bloodAngels": "Blood Angels",
  "darkAngels": "Dark Angels",
  "deathwatch": "Deathwatch",
  "imperialFists": "Imperial Fists",
  "ironHands": "Iron Hands",
  "ravenGuard": "Raven Guard",
  "salamanders": "Salamanders",
  "spaceMarines": "Space Marines",
  "spaceWolves": "Space Wolves",
  "ultramarines": "Ultramarines",
  "whiteScars": "White Scars",
  "custodes": "Adeptus Custodes",
  "mechanicus": "Adeptus Mechanicus",
  "aeldari": "Aeldari",
  "astra": "Astra Militarum",
  "daemons": "Chaos Daemons",
  "chaosKnights": "Chaos Knights",
  "drukhari": "Drukhari",
  "gsc": "Genestealer Cults",
  "greyKnights": "Grey Knights",
  "chaosMarines": "Chaos Space Marines",
  "deathGuard": "Death Guard",
  "emperorsChildren": "Emperor's Children",
  "thousandSons": "Thousand Sons",
  "worldEaters": "World Eaters",
  "imperialAgents": "Imperial Agents",
  "imperialKnights": "Imperial Knights",
  "votann": "Leagues of Votann",
  "necrons": "Necrons",
  "orks": "Orks",
  "tyranids": "Tyranids",
  "tau": "T'au Empire",
};

export const FACTION_IMAGE_URLS = {
  // 40k imperium
  "sisters": "/images/40k/sororitas.svg",
  "blackTemplars": "/images/40k/blackTemplars.svg",
  "bloodAngels": "/images/40k/bloodAngels.svg",
  "darkAngels": "/images/40k/darkAngels.svg",
  "deathwatch": "/images/40k/deathwatch.svg",
  "imperialFists": "/images/40k/imperialFists.svg",
  "ironHands": "/images/40k/ironHands.svg",
  "ravenGuard": "/images/40k/ravenGuard.svg",
  "salamanders": "/images/40k/salamanders.svg",
  "spaceMarines": "/images/40k/astartes.svg",
  "spaceWolves": "/images/40k/spaceWolves.svg",
  "ultramarines": "/images/40k/ultramarines.svg",
  "whiteScars": "/images/40k/whiteScars.svg",
  "custodes": "/images/40k/custodes.svg",
  "mechanicus": "/images/40k/mechanicus.svg",
  "astra": "/images/40k/militarum.svg",
  "greyKnights": "/images/40k/greyKnights.svg",
  "imperialAgents": "/images/40k/imperialAquila.svg",
  "imperialKnights": "/images/40k/imperialKnights.svg",

  // 40k chaos
  "daemons": "/images/40k/chaosDaemons.svg",
  "chaosKnights": "/images/40k/questorTraitoris.svg",
  "chaosMarines": "/images/40k/hereticAstartes.svg",
  "deathGuard": "/images/40k/deathGuard.svg",
  "emperorsChildren": "/images/40k/emperorsChildren.svg",
  "thousandSons": "/images/40k/thousandSons.svg",
  "worldEaters": "/images/40k/worldEaters.svg",

  // 40k xenos
  "aeldari": "/images/40k/asuryani.svg",
  "drukhari": "/images/40k/drukhari.svg",
  "gsc": "/images/40k/gsc.svg",
  "votann": "/images/40k/votann.svg",
  "necrons": "/images/40k/necrons.svg",
  "orks": "/images/40k/orks.svg",
  "tyranids": "/images/40k/tyranids.svg",
  "tau": "/images/40k/tau.svg",

  // aos chaos
  "khorne": "/images/aos/khorne.svg",
  "tzeentch": "/images/aos/tzeentch.svg",
  "slaanesh": "/images/aos/slaanesh.svg",
  "nurgle": "/images/aos/nurgle.svg",
  "skaven": "/images/aos/skaven.svg",
  "slavesToDarkness": "/images/aos/slavesToDarkness.svg",

  // aos death
  "fleshEaterCourts": "/images/aos/fleshEaterCourts.svg",
  "nighthaunt": "/images/aos/nighthaunt.svg",
  "bonereapers": "/images/aos/bonereapers.svg",
  "gravelords": "/images/aos/gravelords.svg",

  // aos destruction
  "gloomspite": "/images/aos/gloomspite.svg",
  "ironjawz": "/images/aos/ironjawz.svg",
  "kruleboyz": "/images/aos/kruleboyz.svg",
  "ogors": "/images/aos/ogors.svg",
  "sonsOfBehemat": "/images/aos/sonsOfBehemat.svg",

  // aos order
  "citiesOfSigmar": "/images/aos/citiesOfSigmar.svg",
  "daughtersOfKhaine": "/images/aos/daughtersOfKhaine.svg",
  "fyreslayers": "/images/aos/fyreslayers.svg",
  "idonethDeepkin": "/images/aos/idonethDeepkin.svg",
  "kharadronOverlords": "/images/aos/kharadronOverlords.svg",
  "luminethRealmlords": "/images/aos/luminethRealmlords.svg",
  "seraphon": "/images/aos/seraphon.svg",
  "stormcast": "/images/aos/sigmar.svg",
  "sylvaneth": "/images/aos/sylvaneth.svg",
};

export const AOS_FACTION_NAMES = {
  /* Chaos */
  "khorne": "Blades of Khorne",
  "tzeentch": "Disciples of Tzeentch",
  "slaanesh": "Hedonites of Slaanesh",
  "nurgle": "Maggotkin of Nurgle",
  "skaven": "Skaven",
  "slavesToDarkness": "Slaves to Darkness",

  /* Death */
  "fleshEaterCourts": "Flesh-eater Courts",
  "nighthaunt": "Nighthaunt",
  "bonereapers": "Ossiarch Bonereapers",
  "gravelords": "Soulblight Gravelords",

  /* Destruction */
  "gloomspite": "Gloomspite Gitz",
  "ironjawz": "Ironjawz",
  "kruleboyz": "Kruleboyz",
  "ogors": "Ogor Mawtribes",
  "sonsOfBehemat": "Sons of Behemat",

  /* Order */
  "citiesOfSigmar": "Cities of Sigmar",
  "daughtersOfKhaine": "Daughters of Khaine",
  "fyreslayers": "Fyreslayers",
  "idonethDeepkin": "Idoneth Deepkin",
  "kharadronOverlords": "Kharadron Overlords",
  "luminethRealmlords": "Lumineth Realm-lords",
  "seraphon": "Seraphon",
  "stormcast": "Stormcast Eternals",
  "sylvaneth": "Sylvaneth"
};